# This pipeline is for running pyvcell on a VCell model for various initial conditions coming from RNAseq data. 
# Eventually, we will want to run this pipeline for multiple models, but for now we will just run it for one model.
# The input data for this pipeline is a VCell model file (in .vcml format) and a set of initial conditions for the model (in .csv format).
# The output of this pipeline will be a set of simulation results for each set of initial conditions, which will be saved in a specified output directory.
